### PR TITLE
Improving stability

### PR DESCRIPTION
**Pull request by hyschive**
This PR improves the stability of GAMER, especially around low-density valleys.

Major improvement:
1. [INT_OPP_SIGN_0TH_ORDER](https://github.com/gamer-project/gamer/wiki/Runtime-Parameters%3A-Interpolation#INT_OPP_SIGN_0TH_ORDER): Apply 0th-order interpolation if the values to be interpolated change signs in adjacent cells. This prevents from introducing unphysically large velocity in low-density valleys during grid refinement and ghost-cell filling.
2. [OPT__LAST_RESORT_FLOOR](https://github.com/gamer-project/gamer/wiki/Hydro#OPT__LAST_RESORT_FLOOR): When the fluid solver fails and neither 1st-order flux correction ([OPT__1ST_FLUX_CORR](https://github.com/gamer-project/gamer/wiki/Hydro#OPT__1ST_FLUX_CORR)) nor auto dt reduction ([AUTO_REDUCE_DT](https://github.com/gamer-project/gamer/wiki/Runtime-Parameters%3A-Timestep#AUTO_REDUCE_DT)) can help, restore original dt and apply floor values.

Minor improvement:
1. Reduce round-off errors in HLLC when v>>Cs.
2. Revise [INT_MONO_COEFF](https://github.com/gamer-project/gamer/wiki/Runtime-Parameters%3A-Interpolation#INT_MONO_COEFF) by applying only to the smaller slope.
3. Fix a bug in `Flu_FixUp_Flux.cpp` where the array indices were not correctly updated when detecting unphysical results.

@lucyundead and @zengbs, can you help take a look. Thanks!

### CODE REVIEW

**Comment by jzuhone** [comment]
@hyschive I had a crash in an MHD simulation that this solved, so looks good to me!

**Review by jzuhone — APPROVED** [review]

**Comment by hyschive** [comment]
@jzuhone Great to know that!

**Comment by lucyundead** [comment]
@hyschive The changes looks reasonable, the code is indeed more stable than before for some test with nearly uniform density.

**Comment by hyschive** [comment]
@lucyundead Thanks for helping review it!

**Pull request merged**
