### PR TITLE
CDM

### PR DESCRIPTION
**Pull request by hyschive**
### Features
Support `PARTICLE + COMOVING` for CDM cosmological simulations.

### Remaining tasks
- [ ] Zeldovich pancake [to be added in a separate PR]
  - [ ] Gas
  - [ ] CDM
  - [ ] Regard it as a built-in test problem 
  - References
    - [AREPO](https://academic.oup.com/mnras/article/401/2/791/1147356): Sec. 9.2
    - [Heitmann et al. 2005](https://iopscience.iop.org/article/10.1086/432646/pdf): Sec. 3
- [ ] Large-scale structure simulations
  - [x] Compare with Gadget-2
  - [ ] Regard it as a built-in test problem [to be added in a separate PR]

### CODE REVIEW

**Comment by jzuhone** [comment]
@hyschive would this enable DM+gas in cosmo sims, or would that require another PR?

**Comment by hyschive** [comment]
> @hyschive would this enable DM+gas in cosmo sims, or would that require another PR?

@jzuhone In principle, yes, though currently we don't have any test problem to validate it. So one needs to test the gas part carefully before any production run.

**Comment by jzuhone** [comment]
We could set up a Zeldovich pancake problem

**Comment by hyschive** [comment]
@jzuhone Good suggestion. I've added it to the [to-do list](https://github.com/gamer-project/gamer/pull/133#issue-1323362238).

**Comment by hyschive** [comment]
This PR is ready to be merged given the consistency between gadget-2 and gamer below.
fig__gamer-vs-gadget

@jzuhone : @BarryTC will add the test problems of (i) Zeldovich pancake collapse and (ii) CDM large-scale structure formation in separate PRs.

**Comment by jzuhone** [comment]
Beautiful!

**Pull request merged**
